const quotes = [
    "Whatever the weather is, enjoy!",
    "No matter what the weather, always bring your own sunshine",
    "There is no such thing as bad weather, only different kinds of good weather",
    "Dedicate some quality time to yourself, you deserve it",
    "You've been a fool all week, it's time to stop",
    "Someone is scamming you, and it's not us",
    "I'm sorry, friend, it was him/her",
    "Please do not tell that joke again",
    "Today you are very sexy, take advantage of it",
    "Never underestimate the power a good nap",
    "Maybe you're not the only one who needs a big hug today",
    "Yes, she/he still remembers that kiss",
    "The universe is trying to tell you something, by God, pay attention",
    "You deserve a huge portion of chocolate cake",
    "Remember, a punch in the face is socially frowned upon",
    "How long since you changed your toothbrush?",
    "How long are you going to wait to see a doctor?",
    "Today could be a great day to tidy up your messy house",
    "Stay tuned to the phone, who knows",
    "That meeting is going to be horribly boooooring",
    "Just smile and don’t open your mouth, it will be the best",
    "That expected appointment will happen soon",
    "If you were to go back to the past, you couldn't have done it better",
    "If I were you, I would do it again",
    "No buddy, that was not a mistake",
    "That carefree style starts to make you look like a beggar",
    "Write that damn email once",
    "You just missed a good opportunity",
    "And what if it's all your fault?",
    "Do not ignore that thing any longer",
    "Stop reliving that conversation in your head",
    "How long since you listened to your favorite band?",
    "A lazy day like any other",
    "Today you should do whatever the hell you want",
    "Your previous look was much better",
    "Make an effort at work, someone is watching you",
    "And what if today is your lucky day?",
    "You're running away and you know it",
    "Don’t, don’t, don’t resign yourself, please",
    "It's time for a change of look",
    "He/She already knows it",
    "You have to keep trying",
    "She/He still thinks of you",
    "Eat more fruit, fuck",
    "With this time who wants to go to the gym?",
    "You are the living disappointment of your 10 year old self",
    "Nobody died reading a book from time to time",
    "There's a reason why you're alone, obviously",
    "Now you can only do better",
    "Listen to your friends, this time they are right",
    "You need luck, not justice",
    "Your instinct is right",
    "Just smile and nod",
    "Having seen so many shows does not make you an intellectual",
    "Stop giving importance to that stupidity",
    "Your smile is the highlight of someone else’s day",
    "Take that trip you’ve been dreaming of for so long",
    "Don’t do anything you’re not motivated to do",
    "Love yourself, your dog does",
    "It never, never, never takes bad weather to eat ice cream",
    "One day there will be no more opportunities",
    "It's more important to look smart than to be smart",
    "Your talent will make that job awesome",
    "Write the whole thing down and it will be much clearer"
];

export default quotes;
